name: mcpoulsenfine-art
favicon: null
layout_spectrum: 0.3299515354447067
typography_spectrum: 0.01621916564181447
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.2639334436971694
  lightness: 0.6853373683989048
  saturation: 0.6311402376741171
  rhythmicContrast: 0.5351615429390222
purpose: []
